# Generated by Django 4.2.30 on 2026-05-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Board Type',
                'verbose_name_plural': 'Board Types',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('circuit_diagram', models.FileField(upload_to='projects/circuit_diagrams/')),
                ('code_file', models.FileField(upload_to='projects/code_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.boardtype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
