# Generated by Django 4.2.30 on 2026-05-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
