# Generated by Django 4.2.30 on 2026-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_company_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='projects', to='myapp.component'),
        ),
    ]
