# Generated by hand to add ProjectComponent through model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_component_project_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='myapp.project')),
            ],
            options={
                'unique_together': {('project', 'component')},
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='components',
        ),
        migrations.RemoveField(
            model_name='component',
            name='quantity',
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='projects', through='myapp.ProjectComponent', to='myapp.component'),
        ),
    ]
