# Generated by Django 4.2.30 on 2026-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_projectupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='projectupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
